const LYFTA_EXERCISE_LINKS: Record<string, string> = {
  "Easy cardio": "https://www.lyfta.app/exercise/elliptical-machine-walk-7sl",
  "Shoulder circles": "https://www.lyfta.app/exercise/shoulder-circle-9gi",
  "Wall push-up": "https://www.lyfta.app/exercise/decline-push-up-against-wall-8s0",
  "Seated chest press": "https://www.lyfta.app/exercise/cable-seated-chest-press-7rs",
  "Machine fly": "https://www.lyfta.app/exercise/lever-seated-fly-18",
  "Incline chest press machine": "https://www.lyfta.app/exercise/lever-incline-chest-press-47",
  "Shoulder press machine": "https://www.lyfta.app/exercise/lever-shoulder-press-2q",
  "Triceps pushdown": "https://www.lyfta.app/exercise/triceps-pushdown-7e",
  "Doorway chest stretch": "https://www.lyfta.app/exercise/doorway-chest-stretch-male-qxq",
  "Overhead triceps stretch": "https://www.lyfta.app/exercise/overhead-triceps-stretch-6r1",
  "Easy rowing warm-up": "https://www.lyfta.app/exercise/rowing-6ee",
  "Incline push-up": "https://www.lyfta.app/exercise/incline-push-up-6n5",
  "Cable external rotation": "https://www.lyfta.app/exercise/cable-standing-shoulder-external-rotation-85u",
  "Smith incline bench press": "https://www.lyfta.app/exercise/smith-incline-bench-press-1a",
  "Dumbbell bench press": "https://www.lyfta.app/exercise/dumbbell-bench-press-84",
  "Cable fly": "https://www.lyfta.app/exercise/cable-fly-with-chest-supported-8ch",
  "Machine assisted dip": "https://www.lyfta.app/exercise/assisted-triceps-dip-69z",
  "Machine triceps extension": "https://www.lyfta.app/exercise/lever-triceps-extension-1g",
  "Banded shoulder stretch": "https://www.lyfta.app/exercise/resistance-band-shoulder-stretch-behind-the-back-8sw",
  "Thread the needle": "https://www.lyfta.app/exercise/thread-the-needle-pose-female-ql2",
  "Cross-body shoulder stretch": "https://www.lyfta.app/exercise/band-warm-up-shoulder-stretch-7k6",
  "Stationary bike": "https://www.lyfta.app/exercise/stationary-bike-run-7uv",
  "Box squat": "https://www.lyfta.app/exercise/dumbbell-goblet-box-squat-8xv",
  "Glute bridge": "https://www.lyfta.app/exercise/dumbbell-glute-bridge-8qi",
  "Seated leg press": "https://www.lyfta.app/exercise/lever-seated-leg-press-7uk",
  "Seated leg curl": "https://www.lyfta.app/exercise/lever-seated-leg-curl-11",
  "Leg extension": "https://www.lyfta.app/exercise/lever-leg-extension-0b",
  "Hip thrust machine": "https://www.lyfta.app/exercise/lever-hip-thrust-8tw",
  "Seated hip abduction": "https://www.lyfta.app/exercise/lever-seated-hip-abduction-19",
  "Kneeling hip-flexor stretch": "https://www.lyfta.app/exercise/kneeling-hip-flexor-stretch-6c6",
  "Seated hamstring stretch": "https://www.lyfta.app/exercise/exercise-ball-seated-hamstring-stretch-73m",
  "Figure-four stretch": "https://www.lyfta.app/exercise/lying-glute-stretch-6c9",
  "Incline treadmill walk": "https://www.lyfta.app/exercise/walking-on-incline-treadmill-8x5",
  "Bodyweight good morning": "https://www.lyfta.app/exercise/bodyweight-good-morning-qhy",
  "Banded lateral walk": "https://www.lyfta.app/exercise/resistance-band-lateral-walk-7zv",
  "Hack squat": "https://www.lyfta.app/exercise/sled-hack-squat-7xr",
  "Smith machine squat": "https://www.lyfta.app/exercise/smith-squat-21",
  "Lying leg curl": "https://www.lyfta.app/exercise/lever-lying-leg-curl-0c",
  "Seated hip adduction": "https://www.lyfta.app/exercise/lever-seated-hip-adduction-10",
  "Machine calf raise": "https://www.lyfta.app/exercise/lever-calf-raise-3p",
  "Standing quad stretch": "https://www.lyfta.app/exercise/standing-quadriceps-stretch-6c2",
  "Standing calf stretch": "https://www.lyfta.app/exercise/standing-hamstring-and-calf-stretch-with-strap-74g",
  "Bench adductor stretch": "https://www.lyfta.app/exercise/adductor-stretch-6zg",
  "Easy rowing": "https://www.lyfta.app/exercise/rowing-6ee",
  "Band pull-apart": "https://www.lyfta.app/exercise/resistance-band-pull-apart-9ku",
  "Straight-arm pulldown warm-up": "https://www.lyfta.app/exercise/cable-straight-arm-pulldown-6fb",
  "Lat pulldown": "https://www.lyfta.app/exercise/cable-wide-grip-lat-pulldown-7v7",
  "Seated cable row": "https://www.lyfta.app/exercise/cable-seated-row-6x3",
  "Chest-supported row": "https://www.lyfta.app/exercise/lever-t-bar-row-81o",
  "Reverse pec deck": "https://www.lyfta.app/exercise/lever-seated-reverse-fly-12",
  "Lateral raise machine": "https://www.lyfta.app/exercise/lever-lateral-raise-0a",
  "Bench lat stretch": "https://www.lyfta.app/exercise/one-arm-lat-stretch-7ix",
  "Easy stationary bike": "https://www.lyfta.app/exercise/stationary-bike-run-7uv",
  "Scapular pull-up": "https://www.lyfta.app/exercise/scapular-pull-up-6sk",
  "Cat-cow": "https://www.lyfta.app/exercise/cat-cow-stretch-9l6",
  "Assisted pull-up": "https://www.lyfta.app/exercise/assisted-pull-up-69x",
  "Single-arm lat pulldown": "https://www.lyfta.app/exercise/cable-one-arm-lat-pulldown-75z",
  "Cable face pull": "https://www.lyfta.app/exercise/cable-standing-face-pull-qi1",
  "Dumbbell lateral raise": "https://www.lyfta.app/exercise/dumbbell-lateral-raise-6iq",
  "Machine back extension": "https://www.lyfta.app/exercise/lever-back-extension-7uj",
  "Bench child's pose": "https://www.lyfta.app/exercise/child-pose-6zp",
  "Neck side stretch": "https://www.lyfta.app/exercise/neck-side-stretch-79z",
};

export function lyftaExerciseUrl(englishName: string): string {
  return LYFTA_EXERCISE_LINKS[englishName] ?? "https://www.lyfta.app/exercises";
}
