import type { GymEquipment } from "./gym-equipment";

export type TrainingPhase = "warmup" | "main" | "stretch";

export type DiagramKind =
  | "cardio" | "shoulder-circle" | "push" | "fly" | "overhead" | "pressdown"
  | "squat" | "bridge" | "leg-press" | "leg-curl" | "leg-extension" | "abduction"
  | "pulldown" | "row" | "rear-fly" | "lateral" | "chest-stretch" | "arm-stretch"
  | "hip-stretch" | "hamstring-stretch" | "glute-stretch" | "lat-stretch";

export interface PlanExercise {
  id: string;
  phase: TrainingPhase;
  name: string;
  englishName: string;
  dose: string;
  rest?: string;
  target: string;
  equipment: GymEquipment | "无需器械";
  setup: string;
  steps: string[];
  cues: string[];
  mistake: string;
  safety: string;
  diagram: DiagramKind;
  guideUrl?: string;
  log?: { sets: number; reps: number };
}

export interface TrainingDay {
  id: "monday" | "wednesday" | "friday";
  weekday: string;
  title: string;
  focus: string;
  duration: string;
  summary: string;
  exercises: PlanExercise[];
  alternatives: PlanExercise[];
}

// 仅列出当前健身房可完成的动作；器械名称与用户提供的设备清单一致。
export const TRAINING_DAYS: TrainingDay[] = [
  {
    id: "monday",
    weekday: "周一",
    title: "胸与推",
    focus: "胸 · 肩前束 · 肱三头肌",
    duration: "约 50–65 分钟",
    summary: "胸部推举与上斜俯卧撑练胸，随后练肩、三头肌和腹部。每项先试轻重量，保持动作可控。",
    exercises: [
      {
        id: "m-cardio",
        phase: "warmup",
        name: "椭圆机轻走",
        englishName: "Easy cardio",
        dose: "5–7 分钟",
        target: "升高体温、让呼吸微微加快",
        equipment: "椭圆机",
        setup: "选择能自然迈步的阻力或坡度，站稳后再启动。强度以能完整说出一句话为准。",
        steps: ["前 2 分钟保持非常轻松。","中间 3 分钟略微加速，但不要喘。","最后 1–2 分钟放慢，准备活动肩部。"],
        cues: ["肩膀放松","脚掌稳定","不要扶着把手吊住身体"],
        mistake: "一开始就调高阻力，身体还没热便进入疲劳。",
        safety: "若头晕、胸闷或异常气短，立即停止。",
        diagram: "cardio",
        guideUrl: "https://www.puregym.com/blog/how-to-use-gym-equipment/",
      },
      {
        id: "m-shoulder",
        phase: "warmup",
        name: "肩绕环与肩胛后缩",
        englishName: "Shoulder circles",
        dose: "各 10 次 × 2 轮",
        target: "肩关节、肩胛控制",
        equipment: "无需器械",
        setup: "站直，双脚与髋同宽，肋骨不要向前翻。先做小圈，再逐渐放大。",
        steps: ["双肩缓慢向上、向后、向下绕圈 10 次。","手臂伸向两侧做小幅绕环，正反各 10 次。","最后把肩胛骨轻轻向后下方夹紧 2 秒，再放松。"],
        cues: ["动作慢","脖子保持长","只到无痛范围"],
        mistake: "为了画大圈而耸肩、塌腰或甩动手臂。",
        safety: "出现夹痛时缩小幅度；持续疼痛不要进行推举。",
        diagram: "shoulder-circle",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
      {
        id: "m-chest-warmup",
        phase: "warmup",
        name: "胸部推举",
        englishName: "Lever chest press",
        dose: "很轻重量 10–12 次 × 1–2 组",
        rest: "30–45 秒",
        target: "胸大肌为主，肩前束和肱三头辅助",
        equipment: "胸部推举机",
        setup: "调座椅让握把与胸口中部齐平；双脚踩稳，后脑、上背和臀部贴靠垫。先用很轻重量试 8 次。",
        steps: ["吸气准备，肩胛轻轻向后下方固定。","呼气把握把平稳推向前方，肘部仍保留一点弯曲。","吸气用 2–3 秒慢慢回程，握把回到胸侧即止。"],
        cues: ["胸口对准握把","手腕保持直","每次回程都可控"],
        mistake: "耸肩、挺腰借力，或重量落到底后撞击配重片。",
        safety: "肩前侧不舒服时缩小回程幅度；锐痛立即停止。",
        diagram: "push",
        guideUrl: "https://www.puregym.com/exercises/chest/bench-press/seated-chest-press/",
      },
      {
        id: "m-chest-press",
        phase: "main",
        name: "胸部推举",
        englishName: "Lever chest press",
        dose: "3 组 × 8–12 次",
        rest: "90 秒",
        target: "胸大肌为主，肩前束和肱三头辅助",
        equipment: "胸部推举机",
        setup: "调座椅让握把与胸口中部齐平；双脚踩稳，后脑、上背和臀部贴靠垫。先用很轻重量试 8 次。",
        steps: ["吸气准备，肩胛轻轻向后下方固定。","呼气把握把平稳推向前方，肘部仍保留一点弯曲。","吸气用 2–3 秒慢慢回程，握把回到胸侧即止。"],
        cues: ["胸口对准握把","手腕保持直","每次回程都可控"],
        mistake: "耸肩、挺腰借力，或重量落到底后撞击配重片。",
        safety: "肩前侧不舒服时缩小回程幅度；锐痛立即停止。",
        diagram: "push",
        guideUrl: "https://www.puregym.com/exercises/chest/bench-press/seated-chest-press/",
        log: {"sets":3,"reps":12},
      },
      {
        id: "m-smith-push",
        phase: "main",
        name: "史密斯杠上斜俯卧撑",
        englishName: "Smith incline push-up",
        dose: "2 组 × 8–12 次",
        rest: "60–90 秒",
        target: "胸、肱三头肌、肩胛稳定",
        equipment: "史密斯深蹲机",
        setup: "把史密斯杠挂在胸口附近高度，确认两侧挂钩锁牢、杠不会转动脱钩；双手略宽于肩，后退至身体成直线。",
        steps: ["收腹夹臀，肩膀保持远离耳朵。","吸气屈肘，让胸口而不是下巴靠近支撑面。","呼气推回起点，手肘不完全锁死。"],
        cues: ["身体整块移动","肘部约 45°","支撑必须稳固"],
        mistake: "杠未锁牢就开始，或塌腰、伸头代替整个身体下降。",
        safety: "先向各方向轻推确认杠牢固；不能固定的杠不做此动作。",
        diagram: "push",
        guideUrl: "https://www.puregym.com/exercises/chest/press-up/incline-push-ups/",
        log: {"sets":2,"reps":12},
      },
      {
        id: "m-shoulder-press",
        phase: "main",
        name: "肩部推举",
        englishName: "Shoulder press machine",
        dose: "2 组 × 8–12 次",
        rest: "90 秒",
        target: "三角肌、肱三头肌",
        equipment: "肩部推举机",
        setup: "调座椅让握把略低于肩；优先选择掌心相对的中立握法，脚掌和背部贴稳。",
        steps: ["吸气收紧腹部，肩膀保持向下。","呼气把握把推到头顶，肘部不要完全锁死。","吸气缓慢下降，停在舒适深度。"],
        cues: ["头在双臂中间","不塌腰","先轻重量学习轨迹"],
        mistake: "为了推起而抬臀、过度挺腰或把肩膀顶向耳朵。",
        safety: "肩峰区域出现夹痛时停止，不要硬推过疼痛点。",
        diagram: "overhead",
        guideUrl: "https://www.puregym.com/exercises/arms-and-shoulders/shoulder-press/shoulder-press-machine/",
        log: {"sets":2,"reps":12},
      },
      {
        id: "m-alt-triceps-machine",
        phase: "main",
        name: "三头肌训练器伸展",
        englishName: "Machine triceps extension",
        dose: "2 组 × 10–15 次",
        rest: "60 秒",
        target: "肱三头肌",
        equipment: "三头肌训练器",
        setup: "调座椅让肘关节对准器械转轴，胸口或背部贴稳靠垫；手腕保持自然直线。",
        steps: ["上臂贴住支撑垫，吸气准备。","呼气伸直肘部，底部不要猛烈锁死。","吸气慢慢回到肘部弯曲、仍能控制的位置。"],
        cues: ["肘轴对准转轴","上臂不抬","回程慢"],
        mistake: "座椅高度错误，或用肩膀和身体压动握把。",
        safety: "肘尖疼痛时减重并缩短伸直幅度。",
        diagram: "pressdown",
        guideUrl: "https://www.puregym.com/exercises/arms-and-shoulders/tricep-extension/",
        log: {"sets":2,"reps":15},
      },
      {
        id: "m-abs",
        phase: "main",
        name: "腹部训练器卷腹",
        englishName: "Lever seated crunch",
        equipment: "腹部训练器",
        target: "腹直肌",
        setup: "按机身图示调节座椅和胸垫，脚踩稳；选择最轻档，先找到肋骨靠近骨盆的短程动作。",
        steps: ["吸气准备，骨盆保持稳定，双手轻握把手。","呼气收腹，让胸廓缓慢靠近骨盆，不用手臂猛拽。","吸气缓慢回到起始位置，腰部不过度后仰。"],
        cues: ["肋骨靠近骨盆","手臂只扶稳","短程慢做"],
        mistake: "只低头弯脖子，或用髋部折叠和手臂拉拽带动配重。",
        safety: "腰背出现锐痛时停止；靠垫或转轴不合适时先请教练调整。",
        diagram: "row",
        dose: "2 组 × 10–15 次",
        rest: "60–75 秒",
        log: {"sets":2,"reps":15},
        guideUrl: "https://www.lyfta.app/exercises",
      },
      {
        id: "m-chest-stretch",
        phase: "stretch",
        name: "门框胸肌拉伸",
        englishName: "Doorway chest stretch",
        dose: "每侧 20–30 秒 × 2",
        target: "胸大肌、肩前侧",
        equipment: "无需器械",
        setup: "前臂贴住门框，肘部略低于肩，前后站成弓步。",
        steps: ["肩膀向后下方放松。","身体缓慢向前移动，直到胸前出现温和拉伸。","自然呼吸，不弹震；换边重复。"],
        cues: ["拉伸感不是疼痛","肋骨不要外翻","动作缓慢"],
        mistake: "把肘抬得过高，或扭转身体强行追求幅度。",
        safety: "肩前侧刺痛时立刻退出拉伸。",
        diagram: "chest-stretch",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
      {
        id: "m-triceps-stretch",
        phase: "stretch",
        name: "头顶肱三头肌拉伸",
        englishName: "Overhead triceps stretch",
        dose: "每侧 20–30 秒 × 2",
        target: "肱三头肌、背阔肌上部",
        equipment: "无需器械",
        setup: "站直或坐直，一只手沿背后向下，另一只手轻扶该侧肘部。",
        steps: ["收紧腹部，避免腰部前拱。","轻轻把肘部引向头后，直到上臂后侧有拉伸感。","自然呼吸后换边。"],
        cues: ["头不要前伸","不要压颈部","轻柔保持"],
        mistake: "用力扳动肘部，或为了够到背部而过度塌腰。",
        safety: "肩或肘出现锐痛时立即放下手臂，不要继续拉伸。",
        diagram: "arm-stretch",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
    ],
    alternatives: [
      {
        id: "m-alt-treadmill",
        phase: "warmup",
        name: "跑步机快走",
        englishName: "Incline treadmill walk",
        dose: "5–7 分钟",
        target: "升高体温、激活臀腿",
        equipment: "跑步机",
        setup: "先站到跑带两侧再启动，速度从慢走开始；适应后加到 2–4% 小坡度，保持能正常说话。",
        steps: ["前 2 分钟平地慢走。","中间 3 分钟略加坡度并自然摆臂。","最后 1–2 分钟恢复平地，呼吸放缓。"],
        cues: ["身体直立","脚步自然","不吊着扶手"],
        mistake: "坡度过高后整个人趴在扶手上，臀腿反而不工作。",
        safety: "调速时扶稳；膝踝疼痛时取消坡度并减速。",
        diagram: "cardio",
        guideUrl: "https://www.puregym.com/blog/how-to-use-gym-equipment/",
      },
      {
        id: "m-wall-push",
        phase: "warmup",
        name: "墙面俯卧撑",
        englishName: "Wall push-up",
        dose: "10 次 × 2 组",
        rest: "30 秒",
        target: "胸、肱三头肌、肩胛稳定",
        equipment: "无需器械",
        setup: "面向墙站立，手掌略宽于肩、与胸口同高，向后退约一臂距离。",
        steps: ["收紧腹部，让头、背、骨盆和脚踝接近一条直线。","吸气屈肘，胸口缓慢靠近墙面。","呼气推墙回到起点，手肘不要锁死。"],
        cues: ["手肘斜向下约 45°","肩膀远离耳朵","身体整块移动"],
        mistake: "只把头伸向墙，或手肘完全向两侧张开。",
        safety: "肩前侧有锐痛时停止，并把手位调低或咨询教练。",
        diagram: "push",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
      {
        id: "m-alt-external-rotation",
        phase: "warmup",
        name: "绳索肩外旋",
        englishName: "Cable external rotation",
        dose: "每侧 12 次 × 2 组",
        rest: "30 秒",
        target: "肩袖、肩关节稳定",
        equipment: "绳索机",
        setup: "滑轮调到肘部高度并用最轻重量；侧身站立，上臂贴住肋骨，肘部弯曲 90°。",
        steps: ["肩胛轻轻向后下方固定。","保持肘部贴身，把前臂向身体外侧旋转。","到无痛终点停一下，再慢慢回到腹部前方。"],
        cues: ["肘部贴身","重量极轻","只转肩不转腰"],
        mistake: "肘部离开身体，或转动整个躯干来拉动配重。",
        safety: "这不是力量挑战；肩内出现夹痛时立即停止。",
        diagram: "shoulder-circle",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
      {
        id: "m-triceps",
        phase: "main",
        name: "绳索下压",
        englishName: "Triceps pushdown",
        dose: "3 组 × 10–15 次",
        rest: "60 秒",
        target: "肱三头肌",
        equipment: "绳索机",
        setup: "滑轮调高，使用器械配备的下压握柄；退半步，膝盖微屈，躯干略前倾但背部中立。",
        steps: ["上臂贴近身体，肘部固定在肋骨旁。","呼气伸直肘关节，把握柄推向大腿前侧，避免锁死肘部。","吸气慢慢回到前臂接近水平的位置。"],
        cues: ["肘不乱跑","肩膀放松","配重片不相撞"],
        mistake: "用整个身体向下压、肘部前后摆动或手腕弯折。",
        safety: "肘关节不适时减重，并避免用力锁死。",
        diagram: "pressdown",
        guideUrl: "https://www.puregym.com/exercises/arms-and-shoulders/tricep-extension/tricep-pushdowns/",
        log: {"sets":3,"reps":15},
      },
      {
        id: "m-alt-independent-press",
        phase: "main",
        name: "独立肩推",
        englishName: "Shoulder press machine",
        dose: "2 组 × 8–12 次",
        rest: "90 秒",
        target: "三角肌、肱三头肌",
        equipment: "独立肩推机",
        setup: "调座椅让握把略低于肩；优先选择掌心相对的中立握法，脚掌和背部贴稳。",
        steps: ["吸气收紧腹部，肩膀保持向下。","呼气把握把推到头顶，肘部不要完全锁死。","吸气缓慢下降，停在舒适深度。"],
        cues: ["头在双臂中间","不塌腰","先轻重量学习轨迹"],
        mistake: "为了推起而抬臀、过度挺腰或把肩膀顶向耳朵。",
        safety: "肩峰区域出现夹痛时停止，不要硬推过疼痛点。",
        diagram: "overhead",
        guideUrl: "https://www.puregym.com/exercises/arms-and-shoulders/shoulder-press/shoulder-press-machine/",
        log: {"sets":2,"reps":12},
      },
      {
        id: "m-alt-db-lateral",
        phase: "main",
        name: "哑铃侧平举",
        englishName: "Dumbbell lateral raise",
        dose: "2 组 × 12–15 次",
        rest: "60 秒",
        target: "三角肌中束",
        equipment: "哑铃",
        setup: "站直或坐直，哑铃放在身体两侧略靠前；膝盖和肘部都保持轻微弯曲。",
        steps: ["肩膀保持向下，呼气由肘部带动手臂抬起。","抬到接近肩高或无痛高度停一下。","吸气用 2–3 秒缓慢放回。"],
        cues: ["肘部带动","哑铃宁轻勿重","不耸肩"],
        mistake: "用身体甩动，或把手抬得远高于肘部像倒水。",
        safety: "肩部出现疼痛弧时降低高度；不要用惯性冲过疼痛点。",
        diagram: "lateral",
        guideUrl: "https://www.puregym.com/exercises/arms-and-shoulders/lateral-raises/",
        log: {"sets":2,"reps":15},
      },
      {
        id: "m-alt-cross-body",
        phase: "stretch",
        name: "横跨身体肩后侧拉伸",
        englishName: "Across chest shoulder stretch",
        dose: "每侧 20–30 秒 × 2",
        target: "三角肌后束、肩后侧",
        equipment: "无需器械",
        setup: "站直或坐直，胸口朝向正前方；一只手臂抬到胸前，肘部保持微屈。",
        steps: ["另一只手扶在上臂处，不要直接压肘关节。","把手臂轻轻引向胸前，肩膀保持向下。","肩后侧有温和拉伸感时保持，换边。"],
        cues: ["身体朝前","不耸肩","轻柔拉近"],
        mistake: "扭转躯干，或用力压肘导致关节不适。",
        safety: "肩关节内部出现刺痛时停止。",
        diagram: "arm-stretch",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
      {
        id: "m-alt-elbows-back",
        phase: "stretch",
        name: "站姿扩胸拉伸",
        englishName: "Elbows back stretch",
        equipment: "无需器械",
        target: "胸肌、肩前侧",
        setup: "站直，双手轻放在腰侧或髋部，肘部指向身后；肩膀放松，收住肋骨，避免通过腰部后仰扩胸。",
        steps: ["缓慢把双肘向身后靠近，胸口自然打开。","到胸前出现温和牵拉时停留，自然呼吸。","缓慢放松双臂，再重复一次。"],
        cues: ["肩膀向下","肋骨收住","轻柔保持"],
        mistake: "为了让肘部碰到一起而强行夹肩，或把腰部拱起借幅度。",
        safety: "肩前侧夹痛时减少后移幅度；持续疼痛停止。",
        diagram: "chest-stretch",
        dose: "20–30 秒 × 2",
        guideUrl: "https://www.lyfta.app/exercises",
      },
      {
        id: "m-alt-neck",
        phase: "stretch",
        name: "颈侧温和拉伸",
        englishName: "Neck side stretch",
        dose: "每侧 15–20 秒 × 2",
        target: "上斜方肌、颈部侧面",
        equipment: "无需器械",
        setup: "坐直或站直，一只手自然垂向地面；另一只手只轻放在头侧，不主动用力下压。",
        steps: ["肩膀向下放松，目光保持朝前。","把耳朵缓慢靠向对侧肩膀。","颈侧有轻微牵拉时保持，再缓慢回正换边。"],
        cues: ["手不下压","肩膀向下","幅度很小"],
        mistake: "用手猛拉头部，或同时低头和转头制造更大幅度。",
        safety: "出现眩晕、头痛、麻木或放射痛时立即停止。",
        diagram: "arm-stretch",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
    ],
  },
  {
    id: "wednesday",
    weekday: "周三",
    title: "腿与臀",
    focus: "股四头肌 · 腘绳肌 · 臀肌",
    duration: "约 55–70 分钟",
    summary: "大腿推蹬和臀推优先，再做腿弯举、腿屈伸与髋外展。伸展和屈曲共用一台器械，切换模式后检查调节销。",
    exercises: [
      {
        id: "w-treadmill",
        phase: "warmup",
        name: "跑步机快走",
        englishName: "Incline treadmill walk",
        dose: "5–7 分钟",
        target: "升高体温、激活臀腿",
        equipment: "跑步机",
        setup: "先站到跑带两侧再启动，速度从慢走开始；适应后加到 2–4% 小坡度，保持能正常说话。",
        steps: ["前 2 分钟平地慢走。","中间 3 分钟略加坡度并自然摆臂。","最后 1–2 分钟恢复平地，呼吸放缓。"],
        cues: ["身体直立","脚步自然","不吊着扶手"],
        mistake: "坡度过高后整个人趴在扶手上，臀腿反而不工作。",
        safety: "调速时扶稳；膝踝疼痛时取消坡度并减速。",
        diagram: "cardio",
        guideUrl: "https://www.puregym.com/blog/how-to-use-gym-equipment/",
      },
      {
        id: "w-bodyweight-squat",
        phase: "warmup",
        name: "徒手深蹲",
        englishName: "Bodyweight squat",
        equipment: "无需器械",
        target: "髋膝协调、臀腿热身",
        setup: "双脚约肩宽，脚尖略向外，双手向前伸；先做浅蹲，在脚跟不抬、背部自然的范围内练习。",
        steps: ["吸气，髋膝同时弯曲，臀部向后下移动。","膝盖沿脚尖方向，下降到能稳定控制的位置。","呼气用全脚掌站起，顶端不猛烈锁膝。"],
        cues: ["全脚掌踩稳","膝盖跟脚尖","先浅后深"],
        mistake: "追求深度而弓背、脚跟离地，或膝盖明显向内夹。",
        safety: "膝腰出现锐痛时停止；不必强求大腿低于水平。",
        diagram: "squat",
        dose: "8–10 次 × 1–2 组",
        guideUrl: "https://www.lyfta.app/exercises",
        rest: "30 秒",
      },
      {
        id: "w-good-morning",
        phase: "warmup",
        name: "徒手早安式",
        englishName: "Bodyweight good morning",
        dose: "10 次 × 2 组",
        rest: "30 秒",
        target: "髋铰链、臀腿后侧",
        equipment: "无需器械",
        setup: "双脚与髋同宽，手放在髋部或胸前；膝盖微屈，脊柱保持自然，先练很小幅度。",
        steps: ["臀部向后推，躯干从髋部整体前倾。","大腿后侧有拉伸时停止，背部仍保持自然。","呼气夹臀把髋部向前送，回到站直。"],
        cues: ["臀部向后","小腿近似不动","背部保持长"],
        mistake: "把动作做成弯腰低头，或膝盖不断向前蹲。",
        safety: "腰痛时缩小幅度；无法找到髋铰链可先请教练示范。",
        diagram: "squat",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
      {
        id: "w-leg-press",
        phase: "main",
        name: "大腿推蹬",
        englishName: "Seated leg press",
        dose: "3 组 × 10–12 次",
        rest: "90–120 秒",
        target: "股四头肌、臀肌、腘绳肌",
        equipment: "大腿推蹬训练机",
        setup: "按机身说明调好座椅、踏板和安全限位，双脚约肩宽；先用轻重量试动作，下降到腰背仍贴垫的深度。",
        steps: ["吸气收紧腹部，膝盖对准第二脚趾。","呼气用全脚掌推开踏板，顶端膝盖保留微屈。","吸气用 2–3 秒回程，在腰部即将离垫前停止。"],
        cues: ["脚跟不离板","膝盖不锁死","腰背贴垫"],
        mistake: "下放过深导致骨盆卷起，或双手推膝盖帮助完成。",
        safety: "膝盖刺痛时减重并缩小幅度；不要锁膝。",
        diagram: "leg-press",
        guideUrl: "https://www.puregym.com/exercises/legs/quad-exercises/leg-presses/seated-leg-press/",
        log: {"sets":3,"reps":12},
      },
      {
        id: "w-hip-thrust",
        phase: "main",
        name: "臀推机",
        englishName: "Hip thrust machine",
        dose: "3 组 × 8–12 次",
        rest: "90 秒",
        target: "臀大肌",
        equipment: "臀推机",
        setup: "按器械说明调节靠垫和髋部护垫；脚掌与髋同宽，顶端时小腿尽量接近竖直。",
        steps: ["下巴微收、肋骨收住，吸气降低髋部。","呼气踩稳脚跟把髋部推高。","顶端夹臀 1 秒，骨盆保持中立，再慢慢下降。"],
        cues: ["顶端看膝盖方向","腰不反弓","脚跟持续发力"],
        mistake: "用腰椎过伸追求高度，或脚放太远导致大腿后侧主导。",
        safety: "腰部不适时减小幅度或停止；护垫压迫骨盆时重新调整。",
        diagram: "bridge",
        guideUrl: "https://www.puregym.com/exercises/glutes/hip-thrusts/bodyweight-hip-thrust/",
        log: {"sets":3,"reps":12},
      },
      {
        id: "w-leg-curl",
        phase: "main",
        name: "大腿屈曲（腿弯举）",
        englishName: "Seated leg curl",
        dose: "3 组 × 10–15 次",
        rest: "60–75 秒",
        target: "腘绳肌（大腿后侧）",
        equipment: "大腿伸展/屈曲训练机",
        setup: "先按机身图示切换到屈曲模式并锁定调节销；膝轴对准转轴，坐姿时固定大腿压垫，脚垫在脚踝上方。",
        steps: ["背部贴垫，抓住把手固定身体。","呼气把脚跟向下后方卷，底部停 1 秒。","吸气慢慢伸膝回程，不让配重片撞击。"],
        cues: ["髋部不抬起","脚踝放松","回程可控"],
        mistake: "座椅没调好导致膝轴错位，或用臀部离座来借力。",
        safety: "膝后侧不适时立即检查转轴和压垫位置。",
        diagram: "leg-curl",
        guideUrl: "https://www.puregym.com/exercises/legs/hamstring-exercises/hamstring-curls/seated-leg-curl/",
        log: {"sets":3,"reps":15},
      },
      {
        id: "w-leg-extension",
        phase: "main",
        name: "大腿伸展（腿屈伸）",
        englishName: "Leg extension",
        dose: "2 组 × 10–15 次",
        rest: "60–75 秒",
        target: "股四头肌（大腿前侧）",
        equipment: "大腿伸展/屈曲训练机",
        setup: "按机身说明切换到伸展模式并锁好调节销；膝轴对准转轴，脚垫位于脚踝上方，腰背和臀部贴稳。",
        steps: ["抓住把手，呼气伸直双膝。","接近伸直时停 1 秒，但不要猛烈锁死。","吸气用 2–3 秒回到起点。"],
        cues: ["脚尖自然朝前","臀部贴座","慢放比快踢重要"],
        mistake: "用惯性踢起重物，或把脚垫放在胫骨中段。",
        safety: "膝前侧疼痛时减重、缩短伸直范围或跳过此动作。",
        diagram: "leg-extension",
        guideUrl: "https://www.puregym.com/exercises/legs/quad-exercises/leg-extensions/",
        log: {"sets":2,"reps":15},
      },
      {
        id: "w-abduction",
        phase: "main",
        name: "坐姿髋外展",
        englishName: "Seated hip abduction",
        dose: "2 组 × 12–15 次",
        rest: "60 秒",
        target: "臀中肌、臀小肌",
        equipment: "大腿外展训练机",
        setup: "膝外侧贴住垫片，背部贴靠垫；从能控制的较小开合幅度和轻重量开始。",
        steps: ["收紧腹部，双手握住把手。","呼气把双膝向外打开，顶端停 1 秒。","吸气慢慢合回，配重片不要完全落下。"],
        cues: ["骨盆不摇晃","膝盖对称打开","回程更慢"],
        mistake: "身体猛烈前后摆动，用惯性甩开双腿。",
        safety: "髋外侧夹痛时减小幅度；不要为了开得更大而弹震。",
        diagram: "abduction",
        guideUrl: "https://www.puregym.com/exercises/legs/inner-outer-thigh/",
        log: {"sets":2,"reps":15},
      },
      {
        id: "w-alt-quad-stretch",
        phase: "stretch",
        name: "站姿股四头肌拉伸",
        englishName: "Standing quad stretch",
        dose: "每侧 20–30 秒 × 2",
        target: "大腿前侧、髋前侧",
        equipment: "无需器械",
        setup: "一手扶墙站稳，另一手握住同侧脚踝；两侧膝盖靠近，支撑腿保持微屈。",
        steps: ["轻收腹并夹紧被拉伸侧臀部。","膝盖指向地面，脚跟温和靠近臀部。","大腿前侧有牵拉时保持，慢慢放下后换边。"],
        cues: ["膝盖并拢","骨盆微后卷","不要拽脚"],
        mistake: "为了拉得更远而塌腰，或把膝盖甩向身体外侧。",
        safety: "膝盖弯曲不适时减小幅度或停止，别强拉脚踝。",
        diagram: "hip-stretch",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
      {
        id: "w-standing-hamstring",
        phase: "stretch",
        name: "站姿腘绳肌拉伸",
        englishName: "Standing hamstring stretch",
        equipment: "无需器械",
        target: "大腿后侧",
        setup: "一只脚向前小迈半步、脚跟着地，后腿微屈承重；保持背部自然，把双手轻放在后腿大腿上。",
        steps: ["前腿膝盖保持微屈，脚尖自然上翘。","臀部向后推，从髋部向前折叠，到大腿后侧温和牵拉。","自然呼吸保持，再缓慢站直换边。"],
        cues: ["臀部向后","背部保持长","不追求摸脚"],
        mistake: "为了摸脚尖而弓背，或把前膝用力压到完全锁死。",
        safety: "出现从臀部向小腿放射的刺麻感时立即退出。",
        diagram: "hamstring-stretch",
        dose: "每侧 20–30 秒 × 2",
        guideUrl: "https://www.lyfta.app/exercises",
      },
    ],
    alternatives: [
      {
        id: "w-alt-elliptical",
        phase: "warmup",
        name: "椭圆机轻走",
        englishName: "Easy cardio",
        dose: "5–7 分钟",
        target: "升高体温、让呼吸微微加快",
        equipment: "椭圆机",
        setup: "选择能自然迈步的阻力或坡度，站稳后再启动。强度以能完整说出一句话为准。",
        steps: ["前 2 分钟保持非常轻松。","中间 3 分钟略微加速，但不要喘。","最后 1–2 分钟放慢，准备活动肩部。"],
        cues: ["肩膀放松","脚掌稳定","不要扶着把手吊住身体"],
        mistake: "一开始就调高阻力，身体还没热便进入疲劳。",
        safety: "若头晕、胸闷或异常气短，立即停止。",
        diagram: "cardio",
        guideUrl: "https://www.puregym.com/blog/how-to-use-gym-equipment/",
      },
      {
        id: "w-alt-abduction-warmup",
        phase: "warmup",
        name: "坐姿髋外展",
        englishName: "Seated hip abduction",
        dose: "很轻重量 10–12 次 × 1–2 组",
        rest: "30–45 秒",
        target: "臀中肌、臀小肌",
        equipment: "大腿外展训练机",
        setup: "膝外侧贴住垫片，背部贴靠垫；从能控制的较小开合幅度和轻重量开始。",
        steps: ["收紧腹部，双手握住把手。","呼气把双膝向外打开，顶端停 1 秒。","吸气慢慢合回，配重片不要完全落下。"],
        cues: ["骨盆不摇晃","膝盖对称打开","回程更慢"],
        mistake: "身体猛烈前后摆动，用惯性甩开双腿。",
        safety: "髋外侧夹痛时减小幅度；不要为了开得更大而弹震。",
        diagram: "abduction",
        guideUrl: "https://www.puregym.com/exercises/legs/inner-outer-thigh/",
      },
      {
        id: "w-alt-hip-warmup",
        phase: "warmup",
        name: "臀推机",
        englishName: "Hip thrust machine",
        dose: "很轻重量 10–12 次 × 1–2 组",
        rest: "30–45 秒",
        target: "臀大肌",
        equipment: "臀推机",
        setup: "按器械说明调节靠垫和髋部护垫；脚掌与髋同宽，顶端时小腿尽量接近竖直。",
        steps: ["下巴微收、肋骨收住，吸气降低髋部。","呼气踩稳脚跟把髋部推高。","顶端夹臀 1 秒，骨盆保持中立，再慢慢下降。"],
        cues: ["顶端看膝盖方向","腰不反弓","脚跟持续发力"],
        mistake: "用腰椎过伸追求高度，或脚放太远导致大腿后侧主导。",
        safety: "腰部不适时减小幅度或停止；护垫压迫骨盆时重新调整。",
        diagram: "bridge",
        guideUrl: "https://www.puregym.com/exercises/glutes/hip-thrusts/bodyweight-hip-thrust/",
      },
      {
        id: "w-alt-smith-squat",
        phase: "main",
        name: "史密斯深蹲",
        englishName: "Smith machine squat",
        dose: "3 组 × 8–12 次",
        rest: "90–120 秒",
        target: "股四头肌、臀肌",
        equipment: "史密斯深蹲机",
        setup: "杠铃放在斜方肌上部而不是颈椎，双脚略向前；先用空杆确认旋转挂钩和两侧安全限位。",
        steps: ["吸气收紧腹部，旋开挂钩。","臀部向后下方移动，膝盖始终跟随脚尖。","呼气踩稳全脚掌站起，稳定后转腕重新挂钩。"],
        cues: ["空杆先练挂钩","杠不压颈部","脚掌不抬"],
        mistake: "脚站得太靠后、膝盖内扣，或没有设置安全限位。",
        safety: "第一次必须请巡场教练确认杠位和限位；腰膝锐痛立即停止。",
        diagram: "squat",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
        log: {"sets":3,"reps":12},
      },
      {
        id: "w-alt-adduction",
        phase: "main",
        name: "坐姿髋内收",
        englishName: "Seated hip adduction",
        dose: "3 组 × 12–15 次",
        rest: "60 秒",
        target: "大腿内收肌群",
        equipment: "大腿内收训练机",
        setup: "大腿内侧贴住垫片，选择能舒适打开的起始角度；背部贴垫，先用轻重量。",
        steps: ["双手握住把手固定骨盆。","呼气把双腿平稳合拢，中心停 1 秒。","吸气慢慢打开到大腿内侧有轻微拉伸。"],
        cues: ["骨盆不晃","双腿同时合拢","打开要慢"],
        mistake: "开度设得过大，或身体前后甩动借力。",
        safety: "腹股沟刺痛时立即停止，不要强行拉开。",
        diagram: "abduction",
        guideUrl: "https://www.puregym.com/exercises/legs/inner-outer-thigh/",
        log: {"sets":3,"reps":15},
      },
      {
        id: "w-db-rdl",
        phase: "main",
        name: "哑铃罗马尼亚硬拉",
        englishName: "Dumbbell Romanian deadlift",
        equipment: "哑铃",
        target: "臀肌、腘绳肌",
        setup: "双脚与髋同宽，轻哑铃放在大腿前侧；膝盖微屈，先完成徒手早安式，找到髋向后移动的感觉。",
        steps: ["吸气收腹，臀部向后推，哑铃贴近大腿向下移动。","到大腿后侧有牵拉、背部仍自然的位置即可，不必触地。","呼气踩稳脚掌、夹臀站直，顶端不向后仰。"],
        cues: ["臀部向后","哑铃贴腿","腰背不弯"],
        mistake: "把动作做成深蹲，或弯腰低头让哑铃离腿很远。",
        safety: "先由现场教练确认髋铰链动作；腰部疼痛立即停止。",
        diagram: "squat",
        dose: "2 组 × 10–15 次",
        rest: "60–75 秒",
        log: {"sets":2,"reps":15},
        guideUrl: "https://www.lyfta.app/exercises",
      },
      {
        id: "w-goblet",
        phase: "main",
        name: "哑铃高脚杯深蹲",
        englishName: "Goblet squat",
        equipment: "哑铃",
        target: "股四头肌、臀肌",
        setup: "双手在胸前抱住一只轻哑铃，肘部自然向下；脚距约肩宽，先用徒手深蹲确认站距和无痛深度。",
        steps: ["吸气收腹，髋膝同时弯曲，臀部向后下移。","膝盖跟脚尖，下降到脚跟不抬、躯干可控的深度。","呼气用全脚掌推地站起，把哑铃保持在胸前。"],
        cues: ["哑铃靠近胸","脚跟踩稳","膝盖不内扣"],
        mistake: "哑铃离胸太远造成前倾，或重量太大导致起身时塌腰。",
        safety: "选择可以独立拿起放下的重量；膝腰疼痛立即停止。",
        diagram: "squat",
        dose: "2 组 × 10–15 次",
        rest: "60–75 秒",
        log: {"sets":2,"reps":15},
        guideUrl: "https://www.lyfta.app/exercises",
      },
      {
        id: "w-alt-calf-stretch",
        phase: "stretch",
        name: "墙面小腿拉伸",
        englishName: "Wall calf stretch",
        dose: "每侧 20–30 秒 × 2",
        target: "腓肠肌、跟腱周围",
        equipment: "无需器械",
        setup: "双手扶墙，一脚向后迈；后脚脚尖朝前、脚跟踩地，前腿自然弯曲。",
        steps: ["保持后腿膝盖伸直，身体整体向墙靠近。","后侧小腿出现温和牵拉后保持。","再稍弯后膝可拉到更深层的小腿，随后换边。"],
        cues: ["后脚跟贴地","脚尖朝前","不弹震"],
        mistake: "后脚向外转或脚跟离地，让拉伸失去目标。",
        safety: "跟腱出现锐痛时立即退出，不在台阶边缘压脚跟。",
        diagram: "hamstring-stretch",
        guideUrl: "https://www.puregym.com/exercises/legs/calf-exercises/",
      },
      {
        id: "w-alt-hip-flexor",
        phase: "stretch",
        name: "站姿髋屈肌拉伸",
        englishName: "Standing hip flexor stretch",
        equipment: "无需器械",
        dose: "每侧 20–30 秒 × 2",
        target: "髋前侧、髂腰肌",
        setup: "前后脚站成短弓步，前膝微屈、后脚跟自然抬起；双手扶髋，躯干直立，先缩小站距找到平衡。",
        steps: ["轻收腹，把骨盆微微后卷，收紧后腿臀部。","保持腰部自然，身体整体向前移动一点。","后腿髋前侧有温和拉伸时保持，自然呼吸后换边。"],
        cues: ["骨盆微后卷","后腿夹臀","腰不塌"],
        mistake: "一味向前跨大步或后仰塌腰，靠腰部伸展代替髋部活动。",
        safety: "保持平衡并只做小幅度；髋前侧夹痛或膝痛时停止。",
        diagram: "hip-stretch",
        guideUrl: "https://www.lyfta.app/exercises",
      },
      {
        id: "w-alt-adductor",
        phase: "stretch",
        name: "站姿侧弓步内收肌拉伸",
        englishName: "Side lunge stretch",
        equipment: "无需器械",
        dose: "每侧 20–30 秒 × 2",
        target: "大腿内侧",
        setup: "双脚比肩宽，脚尖略向外，双手轻放在大腿上；先用较窄站距，确保脚掌稳定、膝盖能跟随脚尖。",
        steps: ["缓慢把重心移到一侧，屈髋屈膝，另一腿伸展但不锁死。","臀部稍向后，伸展侧大腿内侧有温和牵拉时停住。","保持自然呼吸，缓慢回到中间再换边。"],
        cues: ["重心慢移","脚掌踩稳","不压膝关节"],
        mistake: "强行劈开双腿追求低姿势，或膝盖内扣、身体向前栽。",
        safety: "腹股沟刺痛时立即回正；只到能平稳站回来的幅度。",
        diagram: "glute-stretch",
        guideUrl: "https://www.lyfta.app/exercises",
      },
    ],
  },
  {
    id: "friday",
    weekday: "周五",
    title: "背与肩",
    focus: "背阔肌 · 菱形肌 · 三角肌中后束",
    duration: "约 50–65 分钟",
    summary: "高位划船与独立划船练背，再练肩后侧、肩中束和二头肌。D.Y.划船可替换独立划船，不用把几种划船全部加做。",
    exercises: [
      {
        id: "f-elliptical",
        phase: "warmup",
        name: "椭圆机轻走",
        englishName: "Easy cardio",
        dose: "5–7 分钟",
        target: "升高体温、让呼吸微微加快",
        equipment: "椭圆机",
        setup: "选择能自然迈步的阻力或坡度，站稳后再启动。强度以能完整说出一句话为准。",
        steps: ["前 2 分钟保持非常轻松。","中间 3 分钟略微加速，但不要喘。","最后 1–2 分钟放慢，准备活动肩部。"],
        cues: ["肩膀放松","脚掌稳定","不要扶着把手吊住身体"],
        mistake: "一开始就调高阻力，身体还没热便进入疲劳。",
        safety: "若头晕、胸闷或异常气短，立即停止。",
        diagram: "cardio",
        guideUrl: "https://www.puregym.com/blog/how-to-use-gym-equipment/",
      },
      {
        id: "f-shoulders",
        phase: "warmup",
        name: "肩绕环与肩胛后缩",
        englishName: "Shoulder circles",
        dose: "各 10 次 × 2 轮",
        target: "肩关节、肩胛控制",
        equipment: "无需器械",
        setup: "站直，双脚与髋同宽，肋骨不要向前翻。先做小圈，再逐渐放大。",
        steps: ["双肩缓慢向上、向后、向下绕圈 10 次。","手臂伸向两侧做小幅绕环，正反各 10 次。","最后把肩胛骨轻轻向后下方夹紧 2 秒，再放松。"],
        cues: ["动作慢","脖子保持长","只到无痛范围"],
        mistake: "为了画大圈而耸肩、塌腰或甩动手臂。",
        safety: "出现夹痛时缩小幅度；持续疼痛不要进行推举。",
        diagram: "shoulder-circle",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
      {
        id: "f-row-warmup",
        phase: "warmup",
        name: "独立划船",
        englishName: "Lever row",
        dose: "很轻重量 10–12 次 × 1–2 组",
        rest: "30–45 秒",
        target: "中上背、菱形肌",
        equipment: "独立划船机",
        setup: "调座椅使握把位于下胸附近，胸垫稳稳支撑胸部；两侧选相同轻重量，脚踩稳，先试拉确认活动范围。",
        steps: ["伸臂时肩胛可自然前移，但胸口不离垫。","呼气把肘部向后拉，手腕与前臂保持一线。","顶端停 1 秒，吸气控制回程。"],
        cues: ["胸贴垫","肩膀远离耳朵","肘部向后"],
        mistake: "为了拉得更远而抬胸离垫，或用手腕勾动重量。",
        safety: "胸垫压迫不适时调低重量和位置；无法调整就换坐姿划船。",
        diagram: "row",
        guideUrl: "https://www.puregym.com/exercises/back/rows/incline-row/",
      },
      {
        id: "f-high-row",
        phase: "main",
        name: "高位划船",
        englishName: "Lever high row",
        equipment: "高位划船机",
        target: "背阔肌、上背、肱二头肌",
        setup: "调座椅使胸垫贴住胸部，双脚稳固；握住上方把手，选择两侧相同轻重量，回程不让肩被强行拉起。",
        steps: ["胸口保持贴垫，先让肩膀远离耳朵。","呼气沿机器轨迹把肘部拉向身体两侧下方。","吸气缓慢伸臂回程，保持身体稳定，不松手砸落。"],
        cues: ["胸口贴垫","肘向下后","回程慢"],
        mistake: "耸肩用手臂猛拉，或离开胸垫大幅后仰来完成重量。",
        safety: "调整座椅和起点到无痛范围；肩部夹痛时减重或停止。",
        diagram: "row",
        dose: "3 组 × 8–12 次",
        rest: "90 秒",
        log: {"sets":3,"reps":12},
        guideUrl: "https://www.lyfta.app/exercises",
      },
      {
        id: "f-supported-row",
        phase: "main",
        name: "独立划船",
        englishName: "Lever row",
        dose: "3 组 × 8–12 次",
        rest: "75–90 秒",
        target: "中上背、菱形肌",
        equipment: "独立划船机",
        setup: "调座椅使握把位于下胸附近，胸垫稳稳支撑胸部；两侧选相同轻重量，脚踩稳，先试拉确认活动范围。",
        steps: ["伸臂时肩胛可自然前移，但胸口不离垫。","呼气把肘部向后拉，手腕与前臂保持一线。","顶端停 1 秒，吸气控制回程。"],
        cues: ["胸贴垫","肩膀远离耳朵","肘部向后"],
        mistake: "为了拉得更远而抬胸离垫，或用手腕勾动重量。",
        safety: "胸垫压迫不适时调低重量和位置；无法调整就换坐姿划船。",
        diagram: "row",
        guideUrl: "https://www.puregym.com/exercises/back/rows/incline-row/",
        log: {"sets":3,"reps":12},
      },
      {
        id: "f-alt-face-pull",
        phase: "main",
        name: "绳索面拉",
        englishName: "Cable face pull",
        dose: "2 组 × 12–15 次",
        rest: "60 秒",
        target: "肩后束、肩袖、上背",
        equipment: "绳索机",
        setup: "滑轮调到脸部高度，双手拇指朝向自己握绳；退后让绳索产生张力，膝盖微屈。",
        steps: ["肩膀放松，肋骨收住。","呼气把绳索拉向眉眼高度，同时把绳端分向耳朵两侧。","肩胛轻夹后吸气慢慢伸臂。"],
        cues: ["绳端拉向耳朵","肘部抬起","身体不后仰"],
        mistake: "重量太重导致腰部后仰，或把绳索拉向胸口变成划船。",
        safety: "使用机身配套的分叉绳柄并确认卡扣；没有该握柄时选择哑铃侧平举，勿临时绑接附件。",
        diagram: "rear-fly",
        guideUrl: "https://www.puregym.com/exercises/arms-and-shoulders/rear-delt-exercises/face-pulls/",
        log: {"sets":2,"reps":15},
      },
      {
        id: "f-alt-db-lateral",
        phase: "main",
        name: "哑铃侧平举",
        englishName: "Dumbbell lateral raise",
        dose: "2 组 × 12–15 次",
        rest: "60 秒",
        target: "三角肌中束",
        equipment: "哑铃",
        setup: "站直或坐直，哑铃放在身体两侧略靠前；膝盖和肘部都保持轻微弯曲。",
        steps: ["肩膀保持向下，呼气由肘部带动手臂抬起。","抬到接近肩高或无痛高度停一下。","吸气用 2–3 秒缓慢放回。"],
        cues: ["肘部带动","哑铃宁轻勿重","不耸肩"],
        mistake: "用身体甩动，或把手抬得远高于肘部像倒水。",
        safety: "肩部出现疼痛弧时降低高度；不要用惯性冲过疼痛点。",
        diagram: "lateral",
        guideUrl: "https://www.puregym.com/exercises/arms-and-shoulders/lateral-raises/",
        log: {"sets":2,"reps":15},
      },
      {
        id: "f-biceps",
        phase: "main",
        name: "二头肌训练器弯举",
        englishName: "Lever biceps curl",
        equipment: "二头肌训练器",
        target: "肱二头肌",
        setup: "调整座椅，使上臂自然贴在支撑垫上、肘轴接近器械转轴；轻握把手，肩膀放松，从最轻档开始。",
        steps: ["上臂贴稳，吸气准备，肘部不离开支撑。","呼气弯曲肘关节，把握把向肩前方向卷起。","吸气缓慢伸肘回程，接近伸直即止，不锁死。"],
        cues: ["上臂不抬","手腕保持直","下放两秒"],
        mistake: "通过抬肩和身体后仰拉起重量，或下放时突然把肘部拉直。",
        safety: "肘窝或肘尖疼痛时减重并缩短幅度，持续疼痛就停止。",
        diagram: "row",
        dose: "2 组 × 10–15 次",
        rest: "60–75 秒",
        log: {"sets":2,"reps":15},
        guideUrl: "https://www.lyfta.app/exercises",
      },
      {
        id: "f-back-stretch",
        phase: "stretch",
        name: "站姿抱臂上背拉伸",
        englishName: "Dynamic back stretch",
        equipment: "无需器械",
        target: "上背、肩胛周围",
        setup: "站直，双脚与髋同宽，双手在身前轻握；膝盖微屈，头颈保持自然，不需要任何支撑物。",
        steps: ["呼气把双手轻轻向前伸，肩胛缓慢分开。","上背轻微圆起，腹部保持张力，不塌腰。","吸气放松回正，缓慢往返，不拉到疼痛。"],
        cues: ["手向前伸","肩胛分开","腰不塌"],
        mistake: "把动作做成大幅低头弯腰，或用力耸肩让颈部紧张。",
        safety: "上背温和牵拉即可；颈肩出现刺痛或眩晕时停止。",
        diagram: "lat-stretch",
        dose: "6–8 次慢速往返",
        guideUrl: "https://www.lyfta.app/exercises",
      },
      {
        id: "f-shoulder-stretch",
        phase: "stretch",
        name: "横跨身体肩后侧拉伸",
        englishName: "Across chest shoulder stretch",
        dose: "每侧 20–30 秒 × 2",
        target: "三角肌后束、肩后侧",
        equipment: "无需器械",
        setup: "站直或坐直，胸口朝向正前方；一只手臂抬到胸前，肘部保持微屈。",
        steps: ["另一只手扶在上臂处，不要直接压肘关节。","把手臂轻轻引向胸前，肩膀保持向下。","肩后侧有温和拉伸感时保持，换边。"],
        cues: ["身体朝前","不耸肩","轻柔拉近"],
        mistake: "扭转躯干，或用力压肘导致关节不适。",
        safety: "肩关节内部出现刺痛时停止。",
        diagram: "arm-stretch",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
    ],
    alternatives: [
      {
        id: "f-alt-treadmill",
        phase: "warmup",
        name: "跑步机快走",
        englishName: "Incline treadmill walk",
        dose: "5–7 分钟",
        target: "升高体温、激活臀腿",
        equipment: "跑步机",
        setup: "先站到跑带两侧再启动，速度从慢走开始；适应后加到 2–4% 小坡度，保持能正常说话。",
        steps: ["前 2 分钟平地慢走。","中间 3 分钟略加坡度并自然摆臂。","最后 1–2 分钟恢复平地，呼吸放缓。"],
        cues: ["身体直立","脚步自然","不吊着扶手"],
        mistake: "坡度过高后整个人趴在扶手上，臀腿反而不工作。",
        safety: "调速时扶稳；膝踝疼痛时取消坡度并减速。",
        diagram: "cardio",
        guideUrl: "https://www.puregym.com/blog/how-to-use-gym-equipment/",
      },
      {
        id: "f-alt-external-rotation",
        phase: "warmup",
        name: "绳索肩外旋",
        englishName: "Cable external rotation",
        dose: "每侧 12 次 × 2 组",
        rest: "30 秒",
        target: "肩袖、肩关节稳定",
        equipment: "绳索机",
        setup: "滑轮调到肘部高度并用最轻重量；侧身站立，上臂贴住肋骨，肘部弯曲 90°。",
        steps: ["肩胛轻轻向后下方固定。","保持肘部贴身，把前臂向身体外侧旋转。","到无痛终点停一下，再慢慢回到腹部前方。"],
        cues: ["肘部贴身","重量极轻","只转肩不转腰"],
        mistake: "肘部离开身体，或转动整个躯干来拉动配重。",
        safety: "这不是力量挑战；肩内出现夹痛时立即停止。",
        diagram: "shoulder-circle",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
      {
        id: "f-high-row-warmup",
        phase: "warmup",
        name: "高位划船",
        englishName: "Lever high row",
        equipment: "高位划船机",
        target: "背阔肌、上背、肱二头肌",
        setup: "调座椅使胸垫贴住胸部，双脚稳固；握住上方把手，选择两侧相同轻重量，回程不让肩被强行拉起。",
        steps: ["胸口保持贴垫，先让肩膀远离耳朵。","呼气沿机器轨迹把肘部拉向身体两侧下方。","吸气缓慢伸臂回程，保持身体稳定，不松手砸落。"],
        cues: ["胸口贴垫","肘向下后","回程慢"],
        mistake: "耸肩用手臂猛拉，或离开胸垫大幅后仰来完成重量。",
        safety: "调整座椅和起点到无痛范围；肩部夹痛时减重或停止。",
        diagram: "row",
        dose: "很轻重量 10–12 次 × 1–2 组",
        rest: "30–45 秒",
        guideUrl: "https://www.lyfta.app/exercises",
      },
      {
        id: "f-dy-row",
        phase: "main",
        name: "D.Y.划船",
        englishName: "D.Y. row",
        equipment: "D.Y.划船机",
        target: "背阔肌、肱二头肌",
        setup: "调整座椅和胸垫，让胸口稳定贴住，脚踩稳；按机身图示使用反握把手，手腕与前臂保持直线，先用轻重量。",
        steps: ["肩膀向下放，胸口持续贴住支撑垫。","呼气沿机器弧线把肘部拉向身后、靠近髋部。","吸气缓慢伸臂，允许肩胛自然前移但身体不离垫。"],
        cues: ["反握不折腕","肘靠近身体","胸不离垫"],
        mistake: "为拉得更远而后仰甩动身体，或肘部向两侧大幅张开。",
        safety: "按机器贴纸调节，手腕或肩部疼痛时停止。",
        diagram: "row",
        dose: "2 组 × 10–15 次",
        rest: "60–75 秒",
        log: {"sets":2,"reps":15},
        guideUrl: "https://shop.lifefitness.com/products/hammer-strength-plate-loaded-iso-lateral-d-y-row",
      },
      {
        id: "f-alt-independent-press",
        phase: "main",
        name: "独立肩推",
        englishName: "Shoulder press machine",
        dose: "2 组 × 8–12 次",
        rest: "90 秒",
        target: "三角肌、肱三头肌",
        equipment: "独立肩推机",
        setup: "调座椅让握把略低于肩；优先选择掌心相对的中立握法，脚掌和背部贴稳。",
        steps: ["吸气收紧腹部，肩膀保持向下。","呼气把握把推到头顶，肘部不要完全锁死。","吸气缓慢下降，停在舒适深度。"],
        cues: ["头在双臂中间","不塌腰","先轻重量学习轨迹"],
        mistake: "为了推起而抬臀、过度挺腰或把肩膀顶向耳朵。",
        safety: "肩峰区域出现夹痛时停止，不要硬推过疼痛点。",
        diagram: "overhead",
        guideUrl: "https://www.puregym.com/exercises/arms-and-shoulders/shoulder-press/shoulder-press-machine/",
        log: {"sets":2,"reps":12},
      },
      {
        id: "f-hammer",
        phase: "main",
        name: "哑铃锤式弯举",
        englishName: "Hammer curl",
        equipment: "哑铃",
        target: "肱肌、肱二头肌、前臂",
        setup: "站稳，双手各握一只轻哑铃，掌心相对；膝盖微屈，上臂放在身体两侧，肩膀保持放松。",
        steps: ["保持肘部在身体两侧，呼气缓慢举起哑铃。","掌心始终相对，抬至前臂接近上臂时停顿。","吸气缓慢下放，肘部接近伸直但不锁死。"],
        cues: ["掌心相对","上臂不摆","身体不晃"],
        mistake: "向后挺腰甩起哑铃，或把肘部持续向前送来借力。",
        safety: "选可以全程慢放的重量；手腕和肘部疼痛时停止。",
        diagram: "row",
        dose: "2 组 × 10–15 次",
        rest: "60–75 秒",
        log: {"sets":2,"reps":15},
        guideUrl: "https://www.lyfta.app/exercises",
      },
      {
        id: "f-alt-neck",
        phase: "stretch",
        name: "颈侧温和拉伸",
        englishName: "Neck side stretch",
        dose: "每侧 15–20 秒 × 2",
        target: "上斜方肌、颈部侧面",
        equipment: "无需器械",
        setup: "坐直或站直，一只手自然垂向地面；另一只手只轻放在头侧，不主动用力下压。",
        steps: ["肩膀向下放松，目光保持朝前。","把耳朵缓慢靠向对侧肩膀。","颈侧有轻微牵拉时保持，再缓慢回正换边。"],
        cues: ["手不下压","肩膀向下","幅度很小"],
        mistake: "用手猛拉头部，或同时低头和转头制造更大幅度。",
        safety: "出现眩晕、头痛、麻木或放射痛时立即停止。",
        diagram: "arm-stretch",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
      {
        id: "f-alt-overhead-stretch",
        phase: "stretch",
        name: "头顶肱三头肌拉伸",
        englishName: "Overhead triceps stretch",
        dose: "每侧 20–30 秒 × 2",
        target: "肱三头肌、背阔肌上部",
        equipment: "无需器械",
        setup: "站直或坐直，一只手沿背后向下，另一只手轻扶该侧肘部。",
        steps: ["收紧腹部，避免腰部前拱。","轻轻把肘部引向头后，直到上臂后侧有拉伸感。","自然呼吸后换边。"],
        cues: ["头不要前伸","不要压颈部","轻柔保持"],
        mistake: "用力扳动肘部，或为了够到背部而过度塌腰。",
        safety: "肩或肘出现锐痛时立即放下手臂，不要继续拉伸。",
        diagram: "arm-stretch",
        guideUrl: "https://www.acefitness.org/resources/everyone/exercise-library/",
      },
      {
        id: "f-alt-elbows-back",
        phase: "stretch",
        name: "站姿扩胸拉伸",
        englishName: "Elbows back stretch",
        equipment: "无需器械",
        target: "胸肌、肩前侧",
        setup: "站直，双手轻放在腰侧或髋部，肘部指向身后；肩膀放松，收住肋骨，避免通过腰部后仰扩胸。",
        steps: ["缓慢把双肘向身后靠近，胸口自然打开。","到胸前出现温和牵拉时停留，自然呼吸。","缓慢放松双臂，再重复一次。"],
        cues: ["肩膀向下","肋骨收住","轻柔保持"],
        mistake: "为了让肘部碰到一起而强行夹肩，或把腰部拱起借幅度。",
        safety: "肩前侧夹痛时减少后移幅度；持续疼痛停止。",
        diagram: "chest-stretch",
        dose: "20–30 秒 × 2",
        guideUrl: "https://www.lyfta.app/exercises",
      },
    ],
  },
];

export const PHASE_LABELS: Record<TrainingPhase, { title: string; subtitle: string }> = {
  warmup: { title: "热身", subtitle: "有氧升温，再做当天动作的轻重量预热" },
  main: { title: "正式训练", subtitle: "每组留 2–3 次余力，动作稳定再加重" },
  stretch: { title: "拉伸收尾", subtitle: "温和牵拉，不弹震、不忍痛" },
};
